#!/usr/bin/env bash
# Rebuild the WebAssembly module the site runs on.
#
# The built module is committed so the site deploys as pure static files with
# no build step on Vercel's side — which means it goes stale silently whenever
# the engine, the search or models/net.bin changes. Run this after any of them.
#
# The filename carries a content hash. That is not decoration: an earlier
# version served a fixed filename with `immutable, max-age=31536000`, so
# browsers and the CDN both kept a year-old module while the page's HTML and
# JS updated normally. Fresh code then called an export the old module did not
# have and the board simply never dealt — on the production URL only, because
# a preview URL had never cached anything. A hashed name makes a new build a
# new URL, which no cache can answer from an old copy.
set -euo pipefail
cd "$(dirname "$0")/.."

rustup target add wasm32-unknown-unknown
cargo build --release --target wasm32-unknown-unknown -p dominion-wasm

SRC=target/wasm32-unknown-unknown/release/dominion_wasm.wasm
HASH=$(sha256sum "$SRC" | cut -c1-12)
NAME="dominion_wasm.$HASH.wasm"

rm -f web/public/dominion_wasm.*.wasm
cp "$SRC" "web/public/$NAME"

# The worker reads the name from here rather than having it edited into its
# source, so the generated part stays in one small file.
cat > web/public/engine-version.js <<JS
// Generated by web/build.sh — do not edit.
self.ENGINE_WASM = '$NAME';
JS

ls -la "web/public/$NAME"
echo "wrote web/public/engine-version.js -> $NAME"
echo "serve locally with:  (cd web/public && python3 -m http.server 8000)"
